[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200


[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
